const student = require("./db/models/students.js")
const courses = require("./db/models/courses.js")

let course_description =
  "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum. Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC, making it over 2000 years old."

let university_courses = [
    {
        course: "ACCT 2010",
        title: "Financial Accounting I",
        term: "FA 2025",
        section: "1T",
        instructor: "Umarova Zulaykho",
        days: "Monday",
        times: "9:00a.m - 11:20a.m",
        credit_hours: 3,
        course_description: course_description,
        student_feedbacks: []
    },
    {
        course: "ANSO 1050",
        title: "Global Social Problems",
        term: "FA 2025",
        section: "1T",
        instructor: "Mirakilov Bakhrom",
        days: "Monday",
        times: "7:00p.m - 9:20p.m",
        credit_hours: 3,
        course_description: course_description,
        student_feedbacks: []
    },
    {
        course: "ANSO 1060",
        title: "Introduction to Cultural Anthropology",
        term: "FA 2025",
        section: "2T",
        instructor: "Grosso Sarah",
        days: "Thursday",
        times: "2:00p.m - 4:20p.m",
        credit_hours: 3,
        course_description: course_description,
        student_feedbacks: []
  },
  {
        course: "ARHS 2210",
        title: "Intercultural History of Art",
        term: "FA 2025",
        section: "2T",
        instructor: "Pantic Aleksandar",
        days: "Thursday",
        times: "2:00p.m - 4:20p.m",
        credit_hours: 3,
        course_description: course_description,
        student_feedbacks: []
  },
  {
        course: "COSC 1570",
        title: "Mathematics for Computer Science",
        term: "FA 2025",
        section: "1T",
        instructor: "Nacional Maximo",
        days: "Monday",
        times: "4:30p.m - 6:50p.m",
        credit_hours: 3,
        course_description: course_description,
        student_feedbacks: []
  },
  {
        course: "BUSN 4110",
        title: "Operations Management",
        term: "FA 2025",
        section: "1T",
        instructor: "Tien Sing Gee",
        days: "Friday",
        times: "11:30a.m - 1:50p.m",
        credit_hours: 3,
        course_description: course_description,
        student_feedbacks: []
  },
  {
        course: "BUSN 3150",
        title: "Business Information Systems",
        term: "FA 2025",
        section: "5T",
        instructor: "Lin Kuo-Chun",
        days: "Wednesday",
        times: "4:30p.m - 6:50p.m",
        credit_hours: 3,
        course_description: course_description,
        student_feedbacks: []
  },
  {
        course: "BUSN 2750",
        title: "Introduction to Statistics",
        term: "FA 2025",
        section: "6U",
        instructor: "Abdullayev Farhod",
        days: "Friday",
        times: "7:00p.m - 9:20p.m",
        credit_hours: 3,
        course_description: course_description,
        student_feedbacks: []
  },
  {
        course: "BUSN 2100",
        title: "Business Communications",
        term: "FA 2025",
        section: "6T",
        instructor: "Rasulova Dilfuza",
        days: "Tuesday",
        times: "11:30a.m - 1:50p.m",
        credit_hours: 3,
        course_description: course_description,
        student_feedbacks: []
  },
  {
        course: "BUSN 1000",
        title: "Business Spreadsheets",
        term: "FA 2025",
        section: "4T",
        instructor: "Mukhammedova Azizakhon",
        days: "Wednesday",
        times: "4:30p.m - 6:00p.m",
        credit_hours: 3,
        course_description: course_description,
        student_feedbacks: []
  },
  {
        course: "ECON 3000",
        title: "Basic Economic Modelling",
        term: "FA 2025",
        section: "1T",
        instructor: "Kachina Yulia",
        days: "Thursday",
        times: "9:00a.m - 11:20a.m",
        credit_hours: 3,
        course_description: course_description,
        student_feedbacks: []
  },
  {
        course: "COSC 2810",
        title: "Systems Analysis and Design",
        term: "FA 2025",
        section: "2T",
        instructor: "Ali Subair",
        days: "Monday",
        times: "2:00p.m - 4:20p.m",
        credit_hours: 3,
        course_description: course_description,
        student_feedbacks: []
  },
  {
        course: "COSC 3050",
        title: "Data Structures I",
        term: "FA 2025",
        section: "3T",
        instructor: "Goje Nitin",
        days: "Monday",
        times: "11:30a.m - 1:50p.m",
        credit_hours: 3,
        course_description: course_description,
        student_feedbacks: []
  },
  {
        course: "COSC 3410",
        title: "Computer and Information Security",
        term: "FA 2025",
        section: "1T",
        instructor: "Isroilov Islombek",
        days: "Thursday",
        times: "4:30p.m - 6:50p.m",
        credit_hours: 3,
        course_description: course_description,
        student_feedbacks: []
  },
  {
        course: "COSC 3500",
        title: "IT Project Management",
        term: "FA 2025",
        section: "2T",
        instructor: "Nacional Maximo",
        days: "Wednesday",
        times: "4:30p.m - 6:50p.m",
        credit_hours: 3,
        course_description: course_description,
        student_feedbacks: []
  },
  {
        course: "COSC 3810",
        title: "Principles of Programming Languages",
        term: "FA 2025",
        section: "3T",
        instructor: "Bekov Sanjar",
        days: "Monday",
        times: "4:30p.m - 6:50p.m",
        credit_hours: 3,
        course_description: course_description,
        student_feedbacks: []
  },
  {
        course: "CSIS 1500",
        title: "Introduction to Business Technologies",
        term: "FA 2025",
        section: "1T",
        instructor: "Doniyorbek Ahmadaliev",
        days: "Friday",
        times: "2:00p.m - 4:20p.m",
        credit_hours: 3,
        course_description: course_description,
        student_feedbacks: []
  },
  {
        course: "ENGL 1030",
        title: "Introduction to Literature",
        term: "FA 2025",
        section: "4T",
        instructor: "Khayatova Zarnigor",
        days: "Wednesday",
        times: "11:30a.m - 1:50p.m",
        credit_hours: 3,
        course_description: course_description,
        student_feedbacks: []
  },
  {
        course: "ECON 3020",
        title: "Intermediate Microeconomics",
        term: "FA 2025",
        section: "2T",
        instructor: "Van Rooyen Johan",
        days: "Friday",
        times: "4:30p.m - 6:50p.m",
        credit_hours: 3,
        course_description: course_description,
        student_feedbacks: []
  },
  {
        course: "ECON 3100",
        title: "Issues in Economics",
        term: "FA 2025",
        section: "1T",
        instructor: "Muminov Timur",
        days: "Saturday",
        times: "10:00am - 12:20p.m",
        credit_hours: 3,
        course_description: course_description,
        student_feedbacks: []
  },
]

// for (let i = 0; i < university_courses.length; i++) {
//   courses.create({
//     course: university_courses[i].course,
//     title: university_courses[i].title,
//     term: university_courses[i].term,
//     section: university_courses[i].section,
//     instructor: university_courses[i].instructor,
//     days: university_courses[i].days,
//     times: university_courses[i].times,
//     credit_hours: university_courses[i].credit_hours,
//     course_description: university_courses[i].course_description,
//   })
// }

// student.create({
//     student_email: "abbosshodiev@webster.edu",
//     student_email_password: "Abbos2504",
//     student_courses: student_courses,
//     student_name: "Abbos Shodiev"
// });

// let instructors = [
//     {
//         instructor_name: "Umarova Zulaykho",
//         instructor_courses: [
//             {
//                 course: "ACCT 2010",
//                 title: "Financial Accounting I",
//                 term: "FA 2025",
//                 section: "1T",
//                 instructor: "Umarova Zulaykho",
//                 days: "Monday",
//                 times: "9:00a.m - 11:20a.m",
//                 credit_hours: 3,
//                 course_description: course_description,
//             },
//             {
//                 course: "ACCT 2010",
//                 title: "Financial Accounting I",
//                 term: "FA 2025",
//                 section: "2T",
//                 instructor: "Umarova Zulaykho",
//                 days: "Tuesday",
//                 times: "9:00a.m - 11:20a.m",
//                 credit_hours: 3,
//                 course_description: course_description,
//             },
//             {
//                 course: "ACCT 2010",
//                 title: "Financial Accounting I",
//                 term: "FA 2025",
//                 section: "7T",
//                 instructor: "Umarova Zulaykho",
//                 days: "Monday",
//                 times: "11:30a.m - 1:50p.m",
//                 credit_hours: 3,
//                 course_description: course_description,
//             },
//             {
//                 course: "ACCT 2010",
//                 title: "Financial Accounting I",
//                 term: "FA 2025",
//                 section: "3T",
//                 instructor: "Umarova Zulaykho",
//                 days: "Wednesday",
//                 times: "2:00p.m - 4:20p.m",
//                 credit_hours: 3,
//                 course_description: course_description,
//             }
//         ],
//         instructor_bio: course_description
//     },
//     {
//         instructor_name: "Mirakilov Bakhrom",
//         instructor_courses: [
//             {
//                 course: "ANSO 1050",
//                 title: "Global Social Problems",
//                 term: "FA 2025",
//                 section: "1T",
//                 instructor: "Mirakilov Bakhrom",
//                 days: "Monday",
//                 times: "7:00p.m - 9:20p.m",
//                 credit_hours: 3,
//                 course_description: course_description
//             },
//             {
//                 course: "ANSO 1050",
//                 title: "Global Social Problems",
//                 term: "FA 2025",
//                 section: "1U",
//                 instructor: "Mirakilov Bakhrom",
//                 days: "Thursday",
//                 times: "2:00p.m - 4:20p.m",
//                 credit_hours: 3,
//                 course_description: course_description
//             },
//             {
//                 course: "ANSO 1050",
//                 title: "Global Social Problems",
//                 term: "FA 2025",
//                 section: "2U",
//                 instructor: "Mirakilov Bakhrom",
//                 days: "Thursday",
//                 times: "4:30p.m - 6:50p.m",
//                 credit_hours: 3,
//                 course_description: course_description
//             },
//             {
//                 course: "ANSO 1050",
//                 title: "Global Social Problems",
//                 term: "FA 2025",
//                 section: "3T",
//                 instructor: "Mirakilov Bakhrom",
//                 days: "Tuesday",
//                 times: "7:00p.m - 9:20p.m",
//                 credit_hours: 3,
//                 course_description: course_description
//             }
//         ],
//         instructor_bio: course_description
//     },
//     {
//         instructor_name: "Grosso Sarah",
//         instructor_courses: [
//             {
//                 course: "ANSO 1060",
//                 title: "Introduction to Cultural Anthropology",
//                 term: "FA 2025",
//                 section: "4T",
//                 instructor: "Grosso Sarah",
//                 days: "Thursday",
//                 times: "2:00p.m - 4:20p.m",
//                 credit_hours: 3,
//                 course_description: course_description,
//             },
//             {
//                 course: "ANSO 1060",
//                 title: "Introduction to Cultural Anthropology",
//                 term: "FA 2025",
//                 section: "2T",
//                 instructor: "Grosso Sarah",
//                 days: "Monday",
//                 times: "2:00p.m - 4:20p.m",
//                 credit_hours: 3,
//                 course_description: course_description,
//             },
//             {
//                 course: "ANSO 1060",
//                 title: "Introduction to Cultural Anthropology",
//                 term: "FA 2025",
//                 section: "3T",
//                 instructor: "Grosso Sarah",
//                 days: "Thursday",
//                 times: "4:30p.m - 6:50p.m",
//                 credit_hours: 3,
//                 course_description: course_description,
//             },
//             {
//                 course: "ANSO 1060",
//                 title: "Introduction to Cultural Anthropology",
//                 term: "FA 2025",
//                 section: "1T",
//                 instructor: "Grosso Sarah",
//                 days: "Friday",
//                 times: "2:00p.m - 4:20p.m",
//                 credit_hours: 3,
//                 course_description: course_description
//             }
//         ],
//         instructor_bio: course_description
//     },
//     {
//         instructor_name: "Pantic Aleksandar",
//         instructor_courses: [
//             {
//                 course: "ARHS 2210",
//                 title: "Intercultural History of Art",
//                 term: "FA 2025",
//                 section: "2T",
//                 instructor: "Pantic Aleksandar",
//                 days: "Thursday",
//                 times: "2:00p.m - 4:20p.m",
//                 credit_hours: 3,
//                 course_description: course_description,
//             },
//             {
//                 course: "ARHS 2210",
//                 title: "Intercultural History of Art",
//                 term: "FA 2025",
//                 section: "4T",
//                 instructor: "Pantic Aleksandar",
//                 days: "Wednesday",
//                 times: "2:00p.m - 4:20p.m",
//                 credit_hours: 3,
//                 course_description: course_description,
//             },
//             {
//                 course: "ARHS 2210",
//                 title: "Intercultural History of Art",
//                 term: "FA 2025",
//                 section: "1T",
//                 instructor: "Pantic Aleksandar",
//                 days: "Monday",
//                 times: "2:00p.m - 4:20p.m",
//                 credit_hours: 3,
//                 course_description: course_description,
//             },
//             {
//                 course: "ARHS 2210",
//                 title: "Intercultural History of Art",
//                 term: "FA 2025",
//                 section: "3T",
//                 instructor: "Pantic Aleksandar",
//                 days: "Tuesday",
//                 times: "2:00p.m - 4:20p.m",
//                 credit_hours: 3,
//                 course_description: course_description,
//             }
//         ],
//         instructor_bio: course_description
//     },
//     {
//         instructor_name: "Nacional Maximo",
//         instructor_courses: [
//             {
//                 course: "COSC 1570",
//                 title: "Mathematics for Computer Science",
//                 term: "FA 2025",
//                 section: "2T",
//                 instructor: "Nacional Maximo",
//                 days: "Monday",
//                 times: "4:30p.m - 6:50p.m",
//                 credit_hours: 3,
//                 course_description: course_description,
//             },
//             {
//                 course: "COSC 1570",
//                 title: "Mathematics for Computer Science",
//                 term: "FA 2025",
//                 section: "1T",
//                 instructor: "Nacional Maximo",
//                 days: "Friday",
//                 times: "4:30p.m - 6:50p.m",
//                 credit_hours: 3,
//                 course_description: course_description,
//             },
//             {
//                 course: "COSC 3500",
//                 title: "IT Project Management",
//                 term: "FA 2025",
//                 section: "1T",
//                 instructor: "Nacional Maximo",
//                 days: "Wednesday",
//                 times: "4:30p.m - 6:50p.m",
//                 credit_hours: 3,
//                 course_description: course_description,
//             },
//             {
//                 course: "COSC 3500",
//                 title: "IT Project Management",
//                 term: "FA 2025",
//                 section: "3T",
//                 instructor: "Nacional Maximo",
//                 days: "Monday",
//                 times: "11:30a.m - 1:50p.m",
//                 credit_hours: 3,
//                 course_description: course_description
//             },
//             {
//                 course: "COSC 3500",
//                 title: "IT Project Management",
//                 term: "FA 2025",
//                 section: "2T",
//                 instructor: "Nacional Maximo",
//                 days: "Thursday",
//                 times: "2:00p.m - 4:20p.m",
//                 credit_hours: 3,
//                 course_description: course_description,
//           }
//         ],
//         instructor_bio: course_description
//   },
//   {
//       instructor_name: "Tien Sing Gee",
//       instructor_courses: [
//           {
//               course: "BUSN 4110",
//               title: "Operations Management",
//               term: "FA 2025",
//               section: "1T",
//               instructor: "Tien Sing Gee",
//               days: "Friday",
//               times: "11:30a.m - 1:50p.m",
//               credit_hours: 3,
//               course_description: course_description,
//           },
//           {
//               course: "BUSN 4110",
//               title: "Operations Management",
//               term: "FA 2025",
//               section: "3T",
//               instructor: "Tien Sing Gee",
//               days: "Thursday",
//               times: "9:00a.m - 11:20a.m",
//               credit_hours: 3,
//               course_description: course_description,
//           },
//           {
//               course: "BUSN 4110",
//               title: "Operations Management",
//               term: "FA 2025",
//               section: "4T",
//               instructor: "Tien Sing Gee",
//               days: "Tuesday",
//               times: "9:00a.m - 11:20a.m",
//               credit_hours: 3,
//               course_description: course_description,
//           },
//           {
//               course: "BUSN 4110",
//               title: "Operations Management",
//               term: "FA 2025",
//               section: "2T",
//               instructor: "Tien Sing Gee",
//               days: "Thursday",
//               times: "11:30a.m - 1:50p.m",
//               credit_hours: 3,
//               course_description: course_description,
//           }
//       ],
//       instructor_bio: course_description
//   },
//   {
//       instructor_name: "Lin Kuo-Chun",
//       instructor_courses: [
//         {
//             course: "BUSN 3150",
//             title: "Business Information Systems",
//             term: "FA 2025",
//             section: "5T",
//             instructor: "Lin Kuo-Chun",
//             days: "Wednesday",
//             times: "4:30p.m - 6:50p.m",
//             credit_hours: 3,
//             course_description: course_description
//         },
//         {
//             course: "BUSN 3150",
//             title: "Business Information Systems",
//             term: "FA 2025",
//             section: "2T",
//             instructor: "Lin Kuo-Chun",
//             days: "Monday",
//             times: "4:30p.m - 6:50p.m",
//             credit_hours: 3,
//             course_description: course_description
//         },
//         {
//           course: "BUSN 3150",
//           title: "Business Information Systems",
//           term: "FA 2025",
//           section: "3T",
//           instructor: "Lin Kuo-Chun",
//           days: "Thursday",
//           times: "4:30p.m - 6:50p.m",
//           credit_hours: 3,
//           course_description: course_description
//         },
//         {
//           course: "BUSN 3150",
//           title: "Business Information Systems",
//           term: "FA 2025",
//           section: "1T",
//           instructor: "Lin Kuo-Chun",
//           days: "Friday",
//           times: "4:30p.m - 6:50p.m",
//           credit_hours: 3,
//           course_description: course_description
//         }
//       ],
//       instructor_bio: course_description
//   },
//   {
//       instructor_name: "Abdullayev Farhod",
//       instructor_courses: [
//           {
//               course: "BUSN 2750",
//               title: "Introduction to Statistics",
//               term: "FA 2025",
//               section: "6U",
//               instructor: "Abdullayev Farhod",
//               days: "Friday",
//               times: "7:00p.m - 9:20p.m",
//               credit_hours: 3,
//               course_description: course_description,
//           },
//           {
//               course: "BUSN 2750",
//               title: "Introduction to Statistics",
//               term: "FA 2025",
//               section: "5T",
//               instructor: "Abdullayev Farhod",
//               days: "Monday",
//               times: "7:00p.m - 9:20p.m",
//               credit_hours: 3,
//               course_description: course_description,
//           },
//           {
//               course: "BUSN 2750",
//               title: "Introduction to Statistics",
//               term: "FA 2025",
//               section: "2U",
//               instructor: "Abdullayev Farhod",
//               days: "Wednesday",
//               times: "7:00p.m - 9:20p.m",
//               credit_hours: 3,
//               course_description: course_description,
//           },
//       ],
//       instructor_bio: course_description
//   },
//   {
//       instructor_name: "Rasulova Dilfuza",
//       instructor_courses: [
//           {
//               course: "BUSN 2100",
//               title: "Business Communications",
//               term: "FA 2025",
//               section: "6T",
//               instructor: "Rasulova Dilfuza",
//               days: "Tuesday",
//               times: "11:30a.m - 1:50p.m",
//               credit_hours: 3,
//               course_description: course_description,
//           },
//           {
//               course: "BUSN 2100",
//               title: "Business Communications",
//               term: "FA 2025",
//               section: "5T",
//               instructor: "Rasulova Dilfuza",
//               days: "Thursday",
//               times: "11:30a.m - 1:50p.m",
//               credit_hours: 3,
//               course_description: course_description,
//           },
//           {
//               course: "BUSN 2100",
//               title: "Business Communications",
//               term: "FA 2025",
//               section: "4T",
//               instructor: "Rasulova Dilfuza",
//               days: "Friday",
//               times: "11:30a.m - 1:50p.m",
//               credit_hours: 3,
//               course_description: course_description,
//           },
//           {
//               course: "BUSN 2100",
//               title: "Business Communications",
//               term: "FA 2025",
//               section: "3T",
//               instructor: "Rasulova Dilfuza",
//               days: "Tuesday",
//               times: "9:00a.m - 11:20a.m",
//               credit_hours: 3,
//               course_description: course_description,
//           }
//     ],
//     instructor_bio: course_description
//   },
//   {
//       instructor_name: "Mukhammedova Azizakhon",
//       instructor_courses: [
//           {
//               course: "BUSN 1000",
//               title: "Business Spreadsheets",
//               term: "FA 2025",
//               section: "1U",
//               instructor: "Mukhammedova Azizakhon",
//               days: "Wednesday",
//               times: "7:00p.m - 8:30p.m",
//               credit_hours: 3,
//               course_description: course_description,
//           },
//           {
//               course: "BUSN 1000",
//               title: "Business Spreadsheets",
//               term: "FA 2025",
//               section: "6T",
//               instructor: "Mukhammedova Azizakhon",
//               days: "Monday",
//               times: "11:30a.m - 1:00p.m",
//               credit_hours: 3,
//               course_description: course_description,
//           },
//           {
//               course: "BUSN 1000",
//               title: "Business Spreadsheets",
//               term: "FA 2025",
//               section: "1T",
//               instructor: "Mukhammedova Azizakhon",
//               days: "Monday",
//               times: "7:00p.m - 8:30p.m",
//               credit_hours: 3,
//               course_description: course_description,
//           }
//       ],
//       instructor_bio: course_description
//   },
//   {
//       instructor_name: "Kachina Yulia",
//       instructor_courses: [
//           {
//               course: "ECON 3000",
//               title: "Basic Economic Modelling",
//               term: "FA 2025",
//               section: "4T",
//               instructor: "Kachina Yulia",
//               days: "Thursday",
//               times: "9:00a.m - 11:20a.m",
//               credit_hours: 3,
//               course_description: course_description,
//           },
//           {
//               course: "ECON 3000",
//               title: "Basic Economic Modelling",
//               term: "FA 2025",
//               section: "3T",
//               instructor: "Kachina Yulia",
//               days: "Monday",
//               times: "9:00a.m - 11:20a.m",
//               credit_hours: 3,
//               course_description: course_description,
//           },
//           {
//               course: "ECON 3000",
//               title: "Basic Economic Modelling",
//               term: "FA 2025",
//               section: "5T",
//               instructor: "Kachina Yulia",
//               days: "Monday",
//               times: "11:30a.m - 1:50p.m",
//               credit_hours: 3,
//               course_description: course_description,
//           },
//           {
//               course: "ECON 3000",
//               title: "Basic Economic Modelling",
//               term: "FA 2025",
//               section: "7T",
//               instructor: "Kachina Yulia",
//               days: "Wednesday",
//               times: "11:30a.m - 1:50p.m",
//               credit_hours: 3,
//               course_description: course_description
//           }
//       ],
//       instructor_bio: course_description
//   },
//   {
//       instructor_name: "Ali Subair",
//       instructor_courses: [
//           {
//             course: "COSC 2810",
//             title: "Systems Analysis and Design",
//             term: "FA 2025",
//             section: "2T",
//             instructor: "Ali Subair",
//             days: "Monday",
//             times: "2:00p.m - 4:20p.m",
//             credit_hours: 3,
//             course_description: course_description,
//           },
//           {
//             course: "COSC 2810",
//             title: "Systems Analysis and Design",
//             term: "FA 2025",
//             section: "1T",
//             instructor: "Ali Subair",
//             days: "Friday",
//             times: "2:00p.m - 4:20p.m",
//             credit_hours: 3,
//             course_description: course_description,
//           },
//           {
//             course: "COSC 2810",
//             title: "Systems Analysis and Design",
//             term: "FA 2025",
//             section: "3T",
//             instructor: "Ali Subair",
//             days: "Tuesday",
//             times: "2:00p.m - 4:20p.m",
//             credit_hours: 3,
//             course_description: course_description,
//           },
//           {
//             course: "COSC 4110",
//             title: "Database Concepts",
//             term: "FA 2025",
//             section: "1T",
//             instructor: "Ali Subair",
//             days: "Tuesday",
//             times: "9:00a.m - 11:20p.m",
//             credit_hours: 3,
//             course_description: course_description,
//           }
//       ],
//       instructor_bio: course_description
//   },
//   {
//       instructor_name: "Goje Nitin",
//       instructor_courses: [
//           {
//               course: "COSC 3050",
//               title: "Data Structures I",
//               term: "FA 2025",
//               section: "1T",
//               instructor: "Goje Nitin",
//               days: "Monday",
//               times: "11:30a.m - 1:50p.m",
//               credit_hours: 3,
//               course_description: course_description,
//           },
//           {
//             course: "COSC 2670",
//             title: "Network Principles",
//             term: "FA 2025",
//             section: "1T",
//             instructor: "Goje Nitin",
//             days: "Friday",
//             times: "2:00p.m - 4:20p.m",
//             credit_hours: 3,
//             course_description: course_description
//           },
//           {
//             course: "COSC 2670",
//             title: "Network Principles",
//             term: "FA 2025",
//             section: "2T",
//             instructor: "Goje Nitin",
//             days: "Thursday",
//             times: "2:00p.m - 4:20p.m",
//             credit_hours: 3,
//             course_description: course_description
//           },
//           {
//             course: "BUSN 4120",
//             title: "Integrated Business Processes and ERP",
//             term: "FA 2025",
//             section: "1T",
//             instructor: "Goje Nitin",
//             days: "Friday",
//             times: "4:30p.m - 6:50p.m",
//             credit_hours: 3,
//             course_description: course_description
//           },
//           {
//             course: "COSC 1550",
//             title: "Computer Programming I",
//             term: "FA 2025",
//             section: "5T",
//             instructor: "Goje Nitin",
//             days: "Thursday",
//             times: "11:30a.m - 1:50p.m",
//             credit_hours: 3,
//             course_description: course_description,
//           }
//       ],
//       instructor_bio: course_description
//   },
//   {
//         instructor_name: "Computer and Information Security",
//         instructor_courses: [
//             {
//                 course: "COSC 3410",
//                 title: "Computer and Information Security",
//                 term: "FA 2025",
//                 section: "1T",
//                 instructor: "Isroilov Islombek",
//                 days: "Thursday",
//                 times: "4:30p.m - 6:50p.m",
//                 credit_hours: 3,
//                 course_description: course_description,
//             },
//             {
//                 course: "COSC 3410",
//                 title: "Computer and Information Security",
//                 term: "FA 2025",
//                 section: "3T",
//                 instructor: "Isroilov Islombek",
//                 days: "Tuesday",
//                 times: "9:00a.m - 11:20a.m",
//                 credit_hours: 3,
//                 course_description: course_description,
//             },
//             {
//                 course: "CSIS 1500",
//                 title: "Introduction to Business Technologies",
//                 term: "FA 2025",
//                 section: "2T",
//                 instructor: "Isroilov Islombek",
//                 days: "Wednesday",
//                 times: "2:00p.m - 4:20p.m",
//                 credit_hours: 3,
//                 course_description: course_description,
//             },
//             {
//                 course: "CSIS 1500",
//                 title: "Introduction to Business Technologies",
//                 term: "FA 2025",
//                 section: "3T",
//                 instructor: "Isroilov Islombek",
//                 days: "Friday",
//                 times: "4:30p.m - 6:50p.m",
//                 credit_hours: 3,
//                 course_description: course_description,
//             }
//         ],
//         instructor_bio: course_description
//   },
//   {
//         instructor_name: "Bekov Sanjar",
//         instructor_courses: [
//             {
//                 course: "COSC 3810",
//                 title: "Principles of Programming Languages",
//                 term: "FA 2025",
//                 section: "1T",
//                 instructor: "Bekov Sanjar",
//                 days: "Monday",
//                 times: "4:30p.m - 6:50p.m",
//                 credit_hours: 3,
//                 course_description: course_description,
//             },
//             {
//                 course: "COSC 2110",
//                 title: "Computer Languages",
//                 term: "FA 2025",
//                 section: "1T",
//                 instructor: "Bekov Sanjar",
//                 days: "Monday",
//                 times: "2:00p.m - 4:20p.m",
//                 credit_hours: 3,
//                 course_description: course_description,
//             },
//             {
//                 course: "COSC 2110",
//                 title: "Computer Languages",
//                 term: "FA 2025",
//                 section: "4T",
//                 instructor: "Bekov Sanjar",
//                 days: "Wednesday",
//                 times: "4:30p.m - 6:50p.m",
//                 credit_hours: 3,
//                 course_description: course_description,
//             },
//             {
//                 course: "COSC 2110",
//                 title: "Computer Languages",
//                 term: "FA 2025",
//                 section: "3T",
//                 instructor: "Bekov Sanjar",
//                 days: "Tuesday",
//                 times: "2:00p.m - 4:20p.m",
//                 credit_hours: 3,
//                 course_description: course_description,
//             },
//             {
//                 course: "COSC 2110",
//                 title: "Computer Languages",
//                 term: "FA 2025",
//                 section: "2T",
//                 instructor: "Bekov Sanjar",
//                 days: "Wednesday",
//                 times: "2:00p.m - 4:20p.m",
//                 credit_hours: 3,
//                 course_description: course_description,
//             }
//         ],
//         instructor_bio: course_description
//   },
//   {
//         instructor_name: "Doniyorbek Ahmadaliev",
//         instructor_courses: [
//             {
//                 course: "CSIS 1500",
//                 title: "Introduction to Business Technologies",
//                 term: "FA 2025",
//                 section: "1T",
//                 instructor: "Doniyorbek Ahmadaliev",
//                 days: "Friday",
//                 times: "2:00p.m - 4:20p.m",
//                 credit_hours: 3,
//                 course_description: course_description,
//             },
//             {
//                 course: "CSIS 1500",
//                 title: "Introduction to Business Technologies",
//                 term: "FA 2025",
//                 section: "8T",
//                 instructor: "Doniyorbek Ahmadaliev",
//                 days: "Wednesday",
//                 times: "4:30p.m - 6:50p.m",
//                 credit_hours: 3,
//                 course_description: course_description,
//             },
//             {
//                 course: "CSIS 1500",
//                 title: "Introduction to Business Technologies",
//                 term: "FA 2025",
//                 section: "9T",
//                 instructor: "Doniyorbek Ahmadaliev",
//                 days: "Friday",
//                 times: "4:30p.m - 6:50p.m",
//                 credit_hours: 3,
//                 course_description: course_description,
//             }
//         ],
//         instructor_bio: course_description
//   },
//   {
//         instructor_name: "Khayatova Zarnigor",
//         instructor_courses: [
//             {
//                 course: "ENGL 1030",
//                 title: "Introduction to Literature",
//                 term: "FA 2025",
//                 section: "4T",
//                 instructor: "Khayatova Zarnigor",
//                 days: "Wednesday",
//                 times: "11:30a.m - 1:50p.m",
//                 credit_hours: 3,
//                 course_description: course_description,
//             },
//             {
//                 course: "ENGL 1030",
//                 title: "Introduction to Literature",
//                 term: "FA 2025",
//                 section: "2T",
//                 instructor: "Khayatova Zarnigor",
//                 days: "Thursday",
//                 times: "9:00a.m - 11:20a.m",
//                 credit_hours: 3,
//                 course_description: course_description,
//             },
//             {
//                 course: "ENGL 1030",
//                 title: "Introduction to Literature",
//                 term: "FA 2025",
//                 section: "4T",
//                 instructor: "Khayatova Zarnigor",
//                 days: "Wednesday",
//                 times: "11:30a.m - 1:50p.m",
//                 credit_hours: 3,
//                 course_description: course_description,
//             },
//         ],
//         instructor_bio: course_description
//   },
//   {
//         instructor_name: "Van Rooyen Johan",
//         instructor_courses: [
//             {
//                 course: "ECON 3020",
//                 title: "Intermediate Microeconomics",
//                 term: "FA 2025",
//                 section: "2T",
//                 instructor: "Van Rooyen Johan",
//                 days: "Friday",
//                 times: "4:30p.m - 6:50p.m",
//                 credit_hours: 3,
//                 course_description: course_description,
//             },
//             {
//                 course: "ECON 3720",
//                 title: "International Trade and Finance",
//                 term: "FA 2025",
//                 section: "1T",
//                 instructor: "Van Rooyen Johan",
//                 days: "Friday",
//                 times: "9:00a.m - 11:20a.m",
//                 credit_hours: 3,
//                 course_description: course_description,
//             },
//             {
//                 course: "ECON 3020",
//                 title: "Intermediate Microeconomics",
//                 term: "FA 2025",
//                 section: "1T",
//                 instructor: "Van Rooyen Johan",
//                 days: "Friday",
//                 times: "2:00p.m - 4:20p.m",
//                 credit_hours: 3,
//                 course_description: course_description,
//             },
//             {
//                 course: "ECON 3720",
//                 title: "International Trade and Finance",
//                 term: "FA 2025",
//                 section: "2T",
//                 instructor: "Van Rooyen Johan",
//                 days: "Thursday",
//                 times: "9:00a.m - 11:20a.m",
//                 credit_hours: 3,
//                 course_description: course_description,
//             }
//         ],
//         instructor_bio: course_description
//   },
//   {
//         instructor_name: "Muminov Timur",
//         instructor_courses: [
//             {
//                 course: "ECON 3100",
//                 title: "Issues in Economics",
//                 term: "FA 2025",
//                 section: "1T",
//                 instructor: "Muminov Timur",
//                 days: "Saturday",
//                 times: "10:00am - 12:20p.m",
//                 credit_hours: 3,
//                 course_description: course_description,
//             },
//             {
//                 course: "ECON 3100",
//                 title: "Issues in Economics",
//                 term: "FA 2025",
//                 section: "2T",
//                 instructor: "Muminov Timur",
//                 days: "Saturday",
//                 times: "1:30pm - 3:50p.m",
//                 credit_hours: 3,
//                 course_description: course_description,
//             }
//         ],
//         instructor_bio: course_description
//     }
// ]
